"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { BookOpen, CheckCircle2, LoaderCircle } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Invite={email:string;school_name:string;roles:string[];expires_at:string};
export default function InviteSignup({token}:{token:string}){const router=useRouter();const [invite,setInvite]=useState<Invite|null>(null);const [name,setName]=useState("");const [password,setPassword]=useState("");const [status,setStatus]=useState("Checking your invitation…");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
useEffect(()=>{createClient().rpc("inspect_staff_invite",{p_token:token}).then(({data,error})=>{const row=Array.isArray(data)?data[0]:data;if(error||!row){setError("This invitation is invalid, expired, or has already been used.");return}setInvite(row as Invite);setStatus("")})},[token]);
async function submit(e:FormEvent){e.preventDefault();if(!invite)return;setBusy(true);setError("");const supabase=createClient();const origin=location.hostname==="localhost"?"https://hashgacha-app.vercel.app":location.origin;const callback=`${origin}/auth/callback?invite=${encodeURIComponent(token)}&name=${encodeURIComponent(name)}`;const {data,error}=await supabase.auth.signUp({email:invite.email,password,options:{emailRedirectTo:callback,data:{signup_name:name,pending_invite:token}}});if(error){setError(error.message);setBusy(false);return}if(data.session){const result=await supabase.rpc("accept_staff_invite",{p_token:token,p_name:name});if(result.error){setError(result.error.message);setBusy(false);return}router.push("/app");router.refresh();return}setStatus("Check your email to confirm your account. If the final page does not load, return to Hashgacha and sign in—your invitation will finish automatically.");setBusy(false)}
return <main className="auth-page invite-page"><section className="auth-panel"><div className="auth-brand"><span><BookOpen/></span>Hashgacha</div>{error?<div className="invite-state"><h1>Invitation unavailable</h1><p>{error}</p><a href="/login">Return to sign in</a></div>:!invite?<div className="invite-state"><LoaderCircle className="spin"/><p>{status}</p></div>:status?<div className="invite-state success"><CheckCircle2/><h1>Almost there</h1><p>{status}</p></div>:<><div className="auth-copy"><p className="eyebrow">You’re invited</p><h1>Join {invite.school_name}</h1><p>{invite.email} · {invite.roles.map(r=>r[0].toUpperCase()+r.slice(1)).join(", ")}</p></div><form className="auth-form" onSubmit={submit}><label>Your name<div><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Rabbi first and last name"/></div></label><label>Create password<div><input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters"/></div></label><button className="primary auth-submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:"Create account"}</button></form></>}</section><aside className="auth-art"><div><span>A thoughtful beginning</span><h2>Your school invited you into a shared workspace built for clarity and care.</h2></div></aside></main>}
