"use client";

import { useState } from "react";
import { Check, ChevronRight, Clock3, Users } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export type AttendanceStudent={id:string;name:string};
export type AttendanceOffering={id:string;className:string;subject:string;periodName:string;startTime:string;endTime:string;studentIds:string[]};
export type AttendanceRecord={id:string;studentId:string;status:"present"|"late"|"absent"|"excused";lateMinutes:number|null};
export type AttendanceSession={id:string;offeringId:string;status:"active"|"completed";startTime:string;records:AttendanceRecord[]};
export type AttendanceBundle={students:AttendanceStudent[];offerings:AttendanceOffering[];sessions:AttendanceSession[]};

const options=["present","late","absent","excused"] as const;
const labels={present:"Present",late:"Late",absent:"Absent",excused:"Excused"};
const time=(value:string)=>{const [h,m]=value.split(":");const n=Number(h);return `${n%12||12}:${m} ${n>=12?"PM":"AM"}`};

export default function AttendanceView({schoolId,userId,initial}:{schoolId:string;userId:string;initial:AttendanceBundle}){
  const [sessions,setSessions]=useState(initial.sessions);const [selected,setSelected]=useState(initial.sessions.find(s=>s.status==="active")?.offeringId||"");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [lateTarget,setLateTarget]=useState<string|null>(null);const [lateValue,setLateValue]=useState("5");
  const offering=initial.offerings.find(o=>o.id===selected);const session=sessions.find(s=>s.offeringId===selected);const roster=offering?initial.students.filter(s=>offering.studentIds.includes(s.id)):[];
  async function start(offeringId:string){setBusy(true);setError("");const now=new Date();const local=`${String(now.getHours()).padStart(2,"0")}:${String(now.getMinutes()).padStart(2,"0")}:00`;const {data,error}=await createClient().from("attendance_sessions").insert({school_id:schoolId,class_offering_id:offeringId,actual_start_time:local,started_by:userId}).select("id,class_offering_id,status,actual_start_time").single();if(error){setError(error.message);setBusy(false);return}setSessions([...sessions,{id:data.id,offeringId:data.class_offering_id,status:data.status,startTime:data.actual_start_time,records:[]}]);setSelected(offeringId);setBusy(false)}
  async function persistMark(studentId:string,status:typeof options[number],lateMinutes:number|null=null){if(!session)return;setError("");const payload={school_id:schoolId,attendance_session_id:session.id,student_id:studentId,status,late_minutes:lateMinutes,updated_by:userId};const {data,error}=await createClient().from("attendance_records").upsert(payload,{onConflict:"attendance_session_id,student_id"}).select("id,student_id,status,late_minutes").single();if(error){setError(error.message);return}setSessions(sessions.map(s=>s.id===session.id?{...s,records:[...s.records.filter(r=>r.studentId!==studentId),{id:data.id,studentId:data.student_id,status:data.status,lateMinutes:data.late_minutes}]}:s));setLateTarget(null)}
  function mark(studentId:string,status:typeof options[number]){if(status==="late"){setLateTarget(studentId);setLateValue(String(session?.records.find(r=>r.studentId===studentId)?.lateMinutes||5));return}void persistMark(studentId,status)}
  async function markAll(){if(!session||!roster.length)return;setBusy(true);const payload=roster.map(student=>({school_id:schoolId,attendance_session_id:session.id,student_id:student.id,status:"present" as const,late_minutes:null,updated_by:userId}));const {data,error}=await createClient().from("attendance_records").upsert(payload,{onConflict:"attendance_session_id,student_id"}).select("id,student_id,status,late_minutes");if(error){setError(error.message);setBusy(false);return}setSessions(sessions.map(s=>s.id===session.id?{...s,records:(data||[]).map(r=>({id:r.id,studentId:r.student_id,status:r.status,lateMinutes:r.late_minutes}))}:s));setBusy(false)}
  async function complete(){if(!session)return;setBusy(true);const now=new Date();const local=`${String(now.getHours()).padStart(2,"0")}:${String(now.getMinutes()).padStart(2,"0")}:00`;const {error}=await createClient().from("attendance_sessions").update({status:"completed",actual_end_time:local}).eq("id",session.id);if(error){setError(error.message);setBusy(false);return}setSessions(sessions.map(s=>s.id===session.id?{...s,status:"completed"}:s));setSelected("");setBusy(false)}
  if(offering&&session?.status==="active")return <><div className="page-title"><div><h1>Live attendance</h1><p>Attendance only counts after a class is started.</p></div></div>{error&&<p className="form-error attendance-error">{error}</p>}{lateTarget&&<section className="card late-entry" role="dialog" aria-label="Record late arrival"><div><b>How many minutes late?</b><small>{initial.students.find(s=>s.id===lateTarget)?.name}</small></div><input type="number" min="0" autoFocus value={lateValue} onChange={e=>setLateValue(e.target.value)}/><button className="secondary" onClick={()=>setLateTarget(null)}>Cancel</button><button className="primary" onClick={()=>persistMark(lateTarget,"late",Math.max(0,Number(lateValue)||0))}>Save late mark</button></section>}<div className="card live-roster"><div className="live-head"><div><span className="live-label"><i/> LIVE CLASS</span><h2>{offering.className}</h2><p>{offering.periodName} · Started {time(session.startTime)} · {roster.length} students</p></div><button className="secondary" disabled={busy} onClick={complete}>Complete class</button></div><button className="mark-all" disabled={busy||!roster.length} onClick={markAll}><Check/> Mark all present</button>{roster.length?roster.map(student=>{const record=session.records.find(r=>r.studentId===student.id);return <div className="roster-row" key={student.id}><div className="person"><span className="avatar small">{student.name.split(" ").map(n=>n[0]).join("")}</span><b>{student.name}</b></div><div className="segmented">{options.map(option=><button key={option} className={record?.status===option?`selected ${option}`:""} onClick={()=>mark(student.id,option)}>{labels[option]}{option==="late"&&record?.status==="late"?` · ${record.lateMinutes}m`:""}</button>)}</div></div>}):<div className="empty-state"><Users/><p>No students are assigned to this period yet. Add them under Setup → Assignments.</p></div>}</div></>;
  return <><div className="page-title"><div><h1>Today’s classes</h1><p>{new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date())} · {initial.offerings.length} scheduled blocks</p></div></div>{error&&<p className="form-error attendance-error">{error}</p>}<div className="class-list">{initial.offerings.length?initial.offerings.map(o=>{const existing=sessions.find(s=>s.offeringId===o.id);return <div className="card class-card" key={o.id}><div className="class-time"><Clock3/><b>{time(o.startTime)}–{time(o.endTime)}</b></div><div><h3>{o.className}</h3><p>{o.subject} · {o.studentIds.length} students · {o.periodName}</p></div>{existing?.status==="completed"?<span className="status good">Completed</span>:existing?<button className="primary" onClick={()=>setSelected(o.id)}>Resume <ChevronRight size={17}/></button>:<button className="primary" disabled={busy} onClick={()=>start(o.id)}>Start class <ChevronRight size={17}/></button>}</div>}):<div className="card empty-state"><Clock3/><p>No class offerings are scheduled for today. A principal can create them in Setup.</p></div>}</div></>;
}
