"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Check, Hash, LockKeyhole, MessageCircle, Pencil, Send, Trash2, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export type ChatMessage={id:string;sender_id:string;channel_type:"general"|"class"|"dm";channel_id:string|null;body:string;created_at:string};
export type ChatBundle={staff:{id:string;name:string}[];messages:ChatMessage[]};

export default function ChatView({schoolId,userId,initial}:{schoolId:string;userId:string;initial:ChatBundle}){
  const [channel,setChannel]=useState("general");
  const [messages,setMessages]=useState(initial.messages);
  const [body,setBody]=useState("");
  const [error,setError]=useState("");
  const [sending,setSending]=useState(false);
  const [editing,setEditing]=useState<string|null>(null);
  const [editBody,setEditBody]=useState("");
  const [deleting,setDeleting]=useState<string|null>(null);
  const bottom=useRef<HTMLDivElement>(null);
  const supabase=useMemo(()=>createClient(),[]);
  useEffect(()=>{const sub=supabase.channel(`school-chat-${schoolId}`).on("postgres_changes",{event:"*",schema:"public",table:"chat_messages",filter:`school_id=eq.${schoolId}`},payload=>{if(payload.eventType==="INSERT")setMessages(rows=>rows.some(r=>r.id===(payload.new as ChatMessage).id)?rows:[...rows,payload.new as ChatMessage]);if(payload.eventType==="UPDATE")setMessages(rows=>rows.map(r=>r.id===(payload.new as ChatMessage).id?payload.new as ChatMessage:r));if(payload.eventType==="DELETE")setMessages(rows=>rows.filter(r=>r.id!==(payload.old as ChatMessage).id))}).subscribe();return()=>{void supabase.removeChannel(sub)}},[schoolId,supabase]);
  const recipient=channel.startsWith("dm:")?channel.slice(3):null;
  const visible=messages.filter(m=>recipient?m.channel_type==="dm"&&((m.sender_id===userId&&m.channel_id===recipient)||(m.sender_id===recipient&&m.channel_id===userId)):m.channel_type==="general");
  useEffect(()=>bottom.current?.scrollIntoView({behavior:"smooth"}),[visible.length]);
  async function send(){const text=body.trim();if(!text||sending)return;setSending(true);setError("");const {data,error}=await supabase.from("chat_messages").insert({school_id:schoolId,sender_id:userId,channel_type:recipient?"dm":"general",channel_id:recipient,body:text}).select("*").single();if(error){setError(`Message was not sent: ${error.message}`);setSending(false);return}setMessages(rows=>rows.some(r=>r.id===data.id)?rows:[...rows,data]);setBody("");setSending(false)}
  async function saveEdit(id:string){const text=editBody.trim();if(!text)return;setError("");const {data,error}=await supabase.from("chat_messages").update({body:text}).eq("id",id).select("*").single();if(error){setError(`Message was not updated: ${error.message}`);return}setMessages(rows=>rows.map(r=>r.id===id?data:r));setEditing(null)}
  async function remove(id:string){setError("");const {error}=await supabase.from("chat_messages").delete().eq("id",id);if(error){setError(`Message was not removed: ${error.message}`);return}setMessages(rows=>rows.filter(r=>r.id!==id));setDeleting(null)}
  return <><div className="page-title"><div><p className="eyebrow">Secure staff communication</p><h1>Messages</h1><p>Coordinate school-wide or speak privately with another staff member.</p></div></div><section className="chat-layout"><aside className="card chat-channels"><button className={channel==="general"?"active":""} onClick={()=>setChannel("general")}><Hash/><span><b>General</b><small>All school staff</small></span></button><h3>Direct messages</h3>{initial.staff.filter(s=>s.id!==userId).map(s=><button key={s.id} className={channel===`dm:${s.id}`?"active":""} onClick={()=>setChannel(`dm:${s.id}`)}><span className="avatar small">{s.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</span><span><b>{s.name}</b><small><LockKeyhole/> Private</small></span></button>)}</aside><div className="card chat-room"><div className="chat-head"><div>{recipient?<LockKeyhole/>:<Hash/>}<span><b>{recipient?initial.staff.find(s=>s.id===recipient)?.name:"General"}</b><small>{recipient?"Only you two can read this conversation":"Visible to school staff"}</small></span></div></div><div className="chat-feed">{visible.length?visible.map(m=>{const mine=m.sender_id===userId;return <article key={m.id} className={mine?"chat-message mine":"chat-message"}><div><b>{mine?"You":initial.staff.find(s=>s.id===m.sender_id)?.name||"Staff"}</b><time>{new Date(m.created_at).toLocaleString([], {month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</time>{mine&&<span className="message-actions">{editing===m.id?<><button onClick={()=>saveEdit(m.id)} aria-label="Save message"><Check/></button><button onClick={()=>setEditing(null)} aria-label="Cancel editing"><X/></button></>:deleting===m.id?<><small>Remove?</small><button onClick={()=>remove(m.id)}>Yes</button><button onClick={()=>setDeleting(null)}>No</button></>:<><button onClick={()=>{setEditing(m.id);setEditBody(m.body)}} aria-label="Edit message"><Pencil/></button><button onClick={()=>setDeleting(m.id)} aria-label="Remove message"><Trash2/></button></>}</span>}</div>{editing===m.id?<textarea className="message-edit" value={editBody} onChange={e=>setEditBody(e.target.value)}/>:<p>{m.body}</p>}</article>}):<div className="empty-state"><MessageCircle/><p>No messages here yet. Start the conversation.</p></div>}<div ref={bottom}/></div>{error&&<p className="form-error chat-error">{error}</p>}<div className="chat-compose"><textarea value={body} onChange={e=>setBody(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send()}}} placeholder={recipient?"Write a private message…":"Message all staff…"}/><button className="primary" onClick={send} disabled={!body.trim()||sending} aria-label="Send message">{sending?<span className="sending-dot"/>:<Send/>}</button></div></div></section></>
}
