"use client";

import { useState } from "react";
import { BookOpen, CalendarClock, Check, Clock3, Plus, School, UserRound } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export type PeriodData={id:string;name:string;start_time:string;end_time:string};
export type ClassData={id:string;name:string;subject:string;grade_level:string|null};
export type StaffData={id:string;name:string;roles:string[]};
export type OfferingData={id:string;class_id:string;period_id:string|null;rebbi_id:string;days_of_week:number[]};
type Props={schoolId:string;periods:PeriodData[];classes:ClassData[];staff:StaffData[];offerings:OfferingData[]};

export default function SetupView(props:Props){const [tab,setTab]=useState<"periods"|"classes"|"offerings">("periods");const [periods,setPeriods]=useState(props.periods);const [classes,setClasses]=useState(props.classes);const [offerings,setOfferings]=useState(props.offerings);const [error,setError]=useState("");
return <><div className="page-title"><div><p className="eyebrow">Principal administration</p><h1>School setup</h1><p>Build the timetable foundation before assigning students and taking attendance.</p></div></div><div className="setup-tabs"><button className={tab==="periods"?"active":""} onClick={()=>setTab("periods")}><Clock3/>Periods <span>{periods.length}</span></button><button className={tab==="classes"?"active":""} onClick={()=>setTab("classes")}><BookOpen/>Classes <span>{classes.length}</span></button><button className={tab==="offerings"?"active":""} onClick={()=>setTab("offerings")}><CalendarClock/>Offerings <span>{offerings.length}</span></button></div>{error&&<p className="form-error setup-error">{error}</p>}{tab==="periods"&&<Periods schoolId={props.schoolId} rows={periods} setRows={setPeriods} onError={setError}/>} {tab==="classes"&&<Classes schoolId={props.schoolId} rows={classes} setRows={setClasses} onError={setError}/>} {tab==="offerings"&&<Offerings schoolId={props.schoolId} rows={offerings} setRows={setOfferings} periods={periods} classes={classes} staff={props.staff} onError={setError}/>}</>}

function Periods({schoolId,rows,setRows,onError}:{schoolId:string;rows:PeriodData[];setRows:(v:PeriodData[])=>void;onError:(v:string)=>void}){const [name,setName]=useState("");const [start,setStart]=useState("09:00");const [end,setEnd]=useState("10:00");async function add(){onError("");const {data,error}=await createClient().from("periods").insert({school_id:schoolId,name,start_time:start,end_time:end,sort_order:rows.length}).select("id,name,start_time,end_time").single();if(error){onError(error.message);return}setRows([...rows,data]);setName("")}return <div className="setup-grid"><section className="card setup-form"><span className="setup-icon"><Clock3/></span><h2>Add a period</h2><p>Periods are shared school-wide time slots used to prevent double-booking.</p><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Morning seder"/></label><div className="field-pair"><label>Starts<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Ends<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><button className="primary" onClick={add} disabled={!name.trim()}><Plus/>Add period</button></section><SetupList title="School periods" empty="No periods yet" rows={rows.map(r=>({id:r.id,title:r.name,detail:`${shortTime(r.start_time)}–${shortTime(r.end_time)}`,icon:<Clock3/>}))}/></div>}

function Classes({schoolId,rows,setRows,onError}:{schoolId:string;rows:ClassData[];setRows:(v:ClassData[])=>void;onError:(v:string)=>void}){const [name,setName]=useState("");const [subject,setSubject]=useState("");const [grade,setGrade]=useState("Shiur Alef");async function add(){onError("");const {data,error}=await createClient().from("classes").insert({school_id:schoolId,name,subject,grade_level:grade}).select("id,name,subject,grade_level").single();if(error){onError(error.message);return}setRows([...rows,data]);setName("");setSubject("")}return <div className="setup-grid"><section className="card setup-form"><span className="setup-icon"><BookOpen/></span><h2>Add a class</h2><p>A class describes the subject and level. Its actual teacher and time are assigned next.</p><label>Class name<input value={name} onChange={e=>setName(e.target.value)} placeholder="9th Grade Gemara"/></label><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Gemara Le’iyun"/></label><label>Grade level<select value={grade} onChange={e=>setGrade(e.target.value)}><option>Shiur Alef</option><option>Shiur Beis</option><option>Shiur Gimmel</option><option>Shiur Daled</option></select></label><button className="primary" onClick={add} disabled={!name.trim()||!subject.trim()}><Plus/>Add class</button></section><SetupList title="Classes" empty="No classes yet" rows={rows.map(r=>({id:r.id,title:r.name,detail:`${r.subject} · ${r.grade_level||"No level"}`,icon:<BookOpen/>}))}/></div>}

function Offerings({schoolId,rows,setRows,periods,classes,staff,onError}:{schoolId:string;rows:OfferingData[];setRows:(v:OfferingData[])=>void;periods:PeriodData[];classes:ClassData[];staff:StaffData[];onError:(v:string)=>void}){const rebbeim=staff.filter(s=>s.roles.includes("rebbi")||s.roles.includes("principal"));const [classId,setClassId]=useState(classes[0]?.id||"");const [periodId,setPeriodId]=useState(periods[0]?.id||"");const [rebbiId,setRebbiId]=useState(rebbeim[0]?.id||"");const [days,setDays]=useState([0,1,2,3,4]);async function add(){onError("");const period=periods.find(p=>p.id===periodId);const {data,error}=await createClient().from("class_offerings").insert({school_id:schoolId,class_id:classId,period_id:periodId,rebbi_id:rebbiId,days_of_week:days,default_start_time:period?.start_time,default_end_time:period?.end_time,is_recurring:true}).select("id,class_id,period_id,rebbi_id,days_of_week").single();if(error){onError(error.message);return}setRows([...rows,data])}const ready=classes.length&&periods.length&&rebbeim.length;return <div className="setup-grid"><section className="card setup-form"><span className="setup-icon"><CalendarClock/></span><h2>Create an offering</h2><p>Connect a class, period, and rebbi into the operational unit used by rosters and attendance.</p>{!ready&&<div className="setup-hint">Add at least one class, period, and staff member before creating an offering.</div>}<label>Class<select value={classId} onChange={e=>setClassId(e.target.value)}>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Period<select value={periodId} onChange={e=>setPeriodId(e.target.value)}>{periods.map(p=><option key={p.id} value={p.id}>{p.name} · {shortTime(p.start_time)}</option>)}</select></label><label>Rebbi<select value={rebbiId} onChange={e=>setRebbiId(e.target.value)}>{rebbeim.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div><span className="field-label">Teaching days</span><div className="day-picker">{["Sun","Mon","Tue","Wed","Thu","Fri"].map((d,i)=><button key={d} className={days.includes(i)?"selected":""} onClick={()=>setDays(days.includes(i)?days.filter(x=>x!==i):[...days,i].sort())}>{days.includes(i)&&<Check/>}{d}</button>)}</div></div><button className="primary" onClick={add} disabled={!ready||!days.length}><Plus/>Create offering</button></section><SetupList title="Class offerings" empty="No offerings yet" rows={rows.map(r=>{const c=classes.find(x=>x.id===r.class_id);const p=periods.find(x=>x.id===r.period_id);const s=staff.find(x=>x.id===r.rebbi_id);return{id:r.id,title:c?.name||"Class",detail:`${p?.name||"No period"} · ${s?.name||"No rebbi"}`,icon:<School/>}})}/></div>}

function SetupList({title,empty,rows}:{title:string;empty:string;rows:{id:string;title:string;detail:string;icon:React.ReactNode}[]}){return <section className="card setup-list"><div className="card-head"><h2>{title}</h2></div>{rows.length?rows.map(r=><div className="setup-row" key={r.id}><span>{r.icon}</span><div><b>{r.title}</b><small>{r.detail}</small></div></div>):<div className="empty-state"><UserRound/><p>{empty}. Use the form to create the first one.</p></div>}</section>}
function shortTime(value:string){const [h,m]=value.split(":");const n=Number(h);return `${n%12||12}:${m} ${n>=12?"PM":"AM"}`}
