drop policy if exists tenant_select on public.mentor_assignments;drop policy if exists tenant_insert on public.mentor_assignments;drop policy if exists tenant_update on public.mentor_assignments;
create policy mentor_assignment_relationship_select on public.mentor_assignments for select to authenticated using(school_id=(select public.current_school_id()) and ((select public.has_role('principal')) or mentor_id=(select auth.uid())));
create policy principal_mentor_assignment_insert on public.mentor_assignments for insert to authenticated with check(school_id=(select public.current_school_id()) and (select public.has_role('principal')));
create policy principal_mentor_assignment_update on public.mentor_assignments for update to authenticated using(school_id=(select public.current_school_id()) and (select public.has_role('principal'))) with check(school_id=(select public.current_school_id()));

drop policy if exists tenant_select on public.mentor_conversations;drop policy if exists tenant_insert on public.mentor_conversations;drop policy if exists tenant_update on public.mentor_conversations;
create policy mentor_conversation_private_select on public.mentor_conversations for select to authenticated using(school_id=(select public.current_school_id()) and (mentor_id=(select auth.uid()) or ((select public.has_role('principal')) and (shared_with_principal or exists(select 1 from public.note_requests nr where nr.mentor_id=mentor_id and nr.student_id=student_id and nr.status='accepted' and nr.ended_early_at is null and nr.expires_at>now())))));
create policy mentor_conversation_owner_insert on public.mentor_conversations for insert to authenticated with check(school_id=(select public.current_school_id()) and mentor_id=(select auth.uid()) and exists(select 1 from public.mentor_assignments ma where ma.mentor_id=(select auth.uid()) and ma.student_id=student_id));
create policy mentor_conversation_owner_update on public.mentor_conversations for update to authenticated using(school_id=(select public.current_school_id()) and mentor_id=(select auth.uid())) with check(school_id=(select public.current_school_id()) and mentor_id=(select auth.uid()));

drop policy if exists tenant_select on public.note_requests;drop policy if exists tenant_insert on public.note_requests;drop policy if exists tenant_update on public.note_requests;
create policy note_request_participant_select on public.note_requests for select to authenticated using(school_id=(select public.current_school_id()) and (principal_id=(select auth.uid()) or mentor_id=(select auth.uid())));
create policy note_request_principal_insert on public.note_requests for insert to authenticated with check(school_id=(select public.current_school_id()) and principal_id=(select auth.uid()) and (select public.has_role('principal')));
create policy note_request_participant_update on public.note_requests for update to authenticated using(school_id=(select public.current_school_id()) and (principal_id=(select auth.uid()) or mentor_id=(select auth.uid()))) with check(school_id=(select public.current_school_id()));

drop policy if exists tenant_select on public.stats_access_requests;drop policy if exists tenant_insert on public.stats_access_requests;drop policy if exists tenant_update on public.stats_access_requests;
create policy stats_request_participant_select on public.stats_access_requests for select to authenticated using(school_id=(select public.current_school_id()) and ((select public.has_role('principal')) or mentor_id=(select auth.uid())));
create policy stats_request_mentor_insert on public.stats_access_requests for insert to authenticated with check(school_id=(select public.current_school_id()) and mentor_id=(select auth.uid()) and (select public.has_role('mashpia')));
create policy stats_request_participant_update on public.stats_access_requests for update to authenticated using(school_id=(select public.current_school_id()) and ((select public.has_role('principal')) or mentor_id=(select auth.uid()))) with check(school_id=(select public.current_school_id()));
